-- AlterTable
ALTER TABLE "CV" ALTER COLUMN "userID" DROP DEFAULT;

-- AddForeignKey
ALTER TABLE "CV" ADD CONSTRAINT "CV_userID_fkey" FOREIGN KEY ("userID") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
